layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: promise.nzubechi.amadi
  # hackerrank: your_username
  # instagram: promise_nzubechi_amadi/
  # keybase: your_username
  # linkedin: promise-amadi-101759a1/
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: Promise_Amadi1
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

theme: jekyll-theme-modernist
